# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: myserver

variables:
  TF_LOG: 'INFO'
  TF_LOG_PATH: '/tmp/terraform_ado.log'

jobs:
- job: AKSRockyWebserverDeploy
  displayName: AKSRockyWebserverDeploy

  steps:
  - script: echo Deploying AKS Rocky Webserver on Azure
    displayName: 'Deploy AKS Rocky Webserver'

  - script: |
      cd aks_webserver_rocky
      terraform init
      terraform validate
      sudo terraform plan
      sudo terraform apply -auto-approve
    displayName: 'Deploy ASK Rocky Webserver'
